### ISSUE TITLE
v6.0.0 Goals & Milestones

### ISSUE THREAD

**Issue by stevebauman** [Adldap2/Adldap2#118]
Due to upcoming small API changes, and in order to follow semver, the new upcoming version of Adldap will be `v6`.

- [x] Improve documentation on every level (**big one**)
- [x] Rework AccountControl object
- [x] More tests
- [x] Multiple connection support
- [x] Rename `Adldap\Classes\` namespace in favor of something more descriptive (maybe `Scopes`?)
- [x] Create a configurable LDAP schema for OpenLDAP support (suggestions?)
- [x] Move Search class into separate namespace
- [x] Create separate API links for `v5` & `v6`
- [x] Create separate branches for `v5.2` & `v6`
- [x] Rework authentication, binding and exceptions

**Comment by jspringe** [comment]
I wouldn't mind tackling some of the tests. I need some practice there anyway. Also maybe add the `ConnectionManager` for v6 or are you planning on adding that sooner?

**Comment by stevebauman** [comment]
I actually implemented a `ConnectonManager` on `dev-master` https://github.com/Adldap2/Adldap2/blob/master/src/Connections/Manager.php for `v6` a couple weeks ago.

What are your thoughts?

**Comment by stevebauman** [comment]
Since I've utilized the naming convention of `Connection\Manager` in `v6` already, would `Connection\Provider` be more suited to dealing with multiple connections? I'm not against rewriting the connection manager in the `master` branch, just looking for honest criticism.

**Comment by joe-meyer** [comment]
Kind of new to this project but based on this it looks like the goal is to add in OpenLDAP support (to some extent?). The project is name ADldap so I'm not sure if the target is to support OpenLDAP servers that are simply acting as replication of Active Directory or if the intent is to support a raw OpenLDAP instance?

If the latter, one of the things that's can be pretty drastically different is the lack of a `memberOf` attribute. This completely changes how you have to determine if a user is part of a group.

**Comment by stevebauman** [comment]
@joe-meyer yea, this is something I'm not 100% sure about. I think there should be *some* limited support for OpenLDAP with Adldap,but not fully supported since there might be too much of a difference between versions. Not to mention I don't actually have an OpenLDAP server for testing, so it's really tricky to support something you don't have access to.

**Comment by joe-meyer** [comment]
That's fair @stevebauman, while OpenLDAP is free to download/install, it is one more thing to commit to maintaining. 

Right now the Models are pretty [hard coded](https://github.com/Adldap2/Adldap2/blob/master/src/Query/Processor.php#L194-L205) into the query processor. To me it seems reasonable to think that a `User` for instance might be different in OpenLDAP vs AD, and it also seems reasonable to assume that someone might be using a modified schema and want additional functionality on these models. To me, these are a function of the schema entirely and the schema should be able to have as many or as few models as it wants. As an example, I might want to create a field on my users to store their dates of birth. This is something the existing user model doesn't accommodate for but I could easily accommodate for if I could extend that model and overwrite what model users mapped to for that specific schema.

**Comment by stevebauman** [comment]
> As an example, I might want to create a field on my users to store their dates of birth. This is something the existing user model doesn't accommodate for but I could easily accommodate for if I could extend that model and overwrite what model users mapped to for that specific schema.

@joe-meyer, are you referring to custom attributes? You can create your own LDAP attributes by assigning the property manually on the model:

```php
$user = $ad->users()->find('jdoe');

$user->dateofbirth = '1992-10-01';

$user->save();
```

**Comment by joe-meyer** [comment]
@stevebauman Touche, but as far as I can tell this package relies on those models being correct and there's not a good way to override / swap out / remove any of those models. Say for instance, I wanted to use this for OpenLDAP where I want to have a User model that doesn't use the MemberOfTrait, right now I don't see any good way to do that on a connection by connection (or rather schema by schema) basis. 

I'm also not necessarily advocating for this package to support OpenLDAP, but allowing someone to hook into it appropriately to leverage the awesome power of the Query Builder and some of that lower level stuff to get results and build their own models seems like something to consider.

**Comment by wranger** [comment]
We use AD as well as OpenLDAP to store our users in.

There are more differences than the memberof:

Login:
- OpenLDAP: dn: uid=whans,ou=W,ou=Mitarbeiter,ou=User,dc=adint,dc=dir
- AD: samaccountname: whans@adint.dir

Schema: (to use your own fileds), you have to declare the objectClass first
- MyOpenldap: 

objectClass: posixAccount
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: eduPerson
objectClass: leupuserprofile
objectClass: dfnEduPerson
objectClass: schacPersonalCharacteristics
objectClass: schacContactLocation
objectClass: schacEmployeeInfo
objectClass: schacLinkageIdentifiers
objectClass: schacEntryMetadata
objectClass: schacEntryConfidentiality
objectClass: schacUserEntitlements
objectClass: schacGroupMembership
objectClass: sambaSamAccount

AD: objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user

Passwords:
OpenLDAP: You decide what hash to use: 
`public function getHashedPassword($pwd)
		{
			$salt = substr(str_shuffle(str_repeat('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',4)),0,4);
			return '{SSHA}' . base64_encode(sha1( $pwd.$salt, TRUE ). $salt);
		}`

AD: Hashes for you

---- If you are interested in, I can add my OpenLDAP class?

@stevebauman: Good work!
